var d = {
  "Automotive": [
      "ADAAA", 
      "Ambient Light Services",
      "Ankaios",
      "APP4MC",
      "ArchE",
      "ADORe",
      "Autowrx",
      "BlueChi",
      "Chariott",
      "Cloe",
      "eCAL",
      "Heimlig",
      "Ibeji",
      "Kuksa",
      "Leda",
      "Leda Incubator",
      "MDM|BL",
      "MOSAIC",
      "Muto",
      "openDuT",
      "OpenMCx",
      "openPASS",
      "OpenXilEnv",
      "p3com",
      "SCM",
      "SDV Blueprints",
      "SDV Developer Console",
      "SommR",
      "Sphinx",
      "SUMO",
      "Tractus-X",
      "uProtocol",
      "Velocitas"
  ],
  "DT": [
      "AAS Model for Java",
      "AAS Web Client",
      "AASX Package Explorer",
      "BaSyx",
      "FA³ST",
      "Semantic Modeling Framework (ESMF)",
      "Service Lifecycle Management"
  ],
  "ECD": [
      "CDT Cloud",
      "Dirigible",
      "EMF Cloud",
      "GLSP",
      "JKube",
      "Langium",
      "Novamoon",
      "Open VSX",
      "OpenSmartCLIDE",
      "Sprotty",
      "Theia",
      "Tools for Cloud Foundry"
  ],
  "Eclipse Project": [
      "Equinox",
      "JDT",
      "PDE",
      "Platform"
  ],
  "EE4J": [
    "Angus",
    "Cargo Tracker",
    "Documentation for Jakarta EE",
    "Epicyro",
    "Examples for Jakarta EE",
    "Exousia",
    "ExpressLy",
    "GlassFish",
    "Gran Sasso",
    "Grizzly",
    "Implementation of JAXB",
    "Jersey",
    "Krazo",
    "Metro",
    "Mojarra",
    "Open DI",
    "OpenMQ",
    "ORB",
    "Parsson",
    "Soteria",
    "Starter for Jakarta EE",
    "Tyrus",
    "WaSP",
    "Yasson",
    "EclipseLink",
    "Jakarta Activation",
    "Jakarta Annotations",
    "Jakarta Authentication",
    "Jakarta Authorization",
    "Jakarta Batch",
    "Jakarta Concurrency",
    "Jakarta Config",
    "Jakarta Connectors",
    "Jakarta Contexts and Dependency Injection",
    "Jakarta Data",
    "Jakarta EE Platform",
    "Jakarta EE TCK",
    "Jakarta Enterprise Beans",
    "Jakarta Expression Language",
    "Jakarta Faces",
    "Jakarta Interceptors",
    "Jakarta JSON Binding",
    "Jakarta JSON Processing",
    "Jakarta Mail",
    "Jakarta Messaging",
    "Jakarta MVC",
    "Jakarta NoSQL",
    "Jakarta Persistence",
    "Jakarta RESTful Web Services",
    "Jakarta RPC",
    "Jakarta Security",
    "Jakarta Server Pages",
    "Jakarta Servlet",
    "Jakarta Stable APIs",
    "Jakarta Standard Tag Library",
    "Jakarta Transactions",
    "Jakarta Validation",
    "Jakarta WebSocket",
    "Jakarta XML Binding",
    "Jakarta XML Web Services"
  ],
  "Adoptium": [
    "Adoptium Incubator",
    "AQAvit",
    "Migration Toolkit for Java",
    "Mission Control",
    "Temurin Compliance",
    "Temurin"
  ],
  "IoT": [
    "4diac",
    "Agail",
    "Amlen",
    "Arrowhead",
    "Californium CoAP Framework",
    "Cyclone DDS",
    "Diafanis",
    "Ditto",
    "Duttile",
    "EdiTDor",
    "Embedded CDT",
    "fog05",
    "hawkBit",
    "Hara",
    "Hono",
    "ioFog",
    "IoT Packages",
    "Kanto",
    "Kapua",
    "Keti",
    "Keyple",
    "Keypop",
    "Kiso-testing",
    "Kura",
    "Leshan",
    "Milo",
    "Mita",
    "Mosquitto",
    "MRAA",
    "OM2M",
    "OneOFour",
    "Paho",
    "Paho Incubator",
    "Streamsheets",
    "Symphony",
    "Tahu",
    "Thingweb",
    "ThreadX",
    "tinydtls",
    "Tocandira",
    "UPM",
    "VOLTTRON",
    "Vorto",
    "Wakaama",
    "Zenoh",
    "Sparkplug"
],
"Location Tech": [
  "GeoGig",
  "GeoMesa",
  "GeoTrellis",
  "GeoWave",
  "JTS Topology Suite",
  "Proj4J",
  "RasterFrames",
  "SFCurve",
  "Spatial4j",
  "uDig",
],
"Modeling": [
  "Agile UML",
  "Amalgam",
  "Capra",
  "Ecore Tools",
  "Edapt",
  "EMF Client Platform",
  "EMF Compare",
  "EMF Parsley",
  "EMF Services",
  "EMFStore",
  "Epsilon",
  "Formal Modeling Project",
  "GEMOC Studio",
  "Gendoc",
  "GMF Runtime",
  "Graphiti",
  "Hawk",
  "Layout Kernel",
  "Model Driven Health Tools",
  "Model Framework Technology (EMFT)",
  "emfatic",
  "Extended Editing Framework (EEF)",
  "EMF Refactor",
  "Henshin",
  "Modeling Framework - Container Project",
  "EMF - CDO",
  "EMF",
  "EMF DM",
  "Generation Factories (EGF)",
  "Modeling Workflow Engine",
  "EMF Teneo Model",
  "Papyrus-RT",
  "POOSL",
  "Sirius",
  "SmartMDSD",
  "SysON",
  "VIATRA",
  "Xpect",
  "Xsemantics",
  "Model Development Tools (MDT)",
  "MDT - BPMN2",
  "eTrice",
  "MDT UML2",
  "MoDisco",
  "OCL",
  "Papyrus",
  "Requirements Modeling Framework",
  "M2T - Acceleo",
  "M2T - Xpand",
  "Model-to-Model Transformation (MMT)",
  "MMT - ATL",
  "QVT Operational",
  "QVTd",
  "Textual Modeling Framework",
  "Xtext"
],
"PolarSys": [
  "B612",
  "Capella",
  "CHESS",
  "Kitalpha",
  "LibIMS",
  "NG661 Designer",
  "OpenCert",
  "Safety Framework",
  "Time4Sys"
],
"Runtime": [
  "Communications Framework",
  "Gemini",
  "Gemini Blueprint",
  "Gemini DBAccess",
  "Gemini JPA",
  "Gemini Management",
  "Gemini Naming",
  "Gemini Web",
  "Jetty - Servlet Engine and Http Server",
  "Remote Application Platform",
  "Remote Application Platform Incubator",
  "Riena",
  "Vert.x",
  "Virgo"
],
"SOA": [
  "BPMN2 Modeler Project",
  "Winery"
],
"Technology": [
  "SimRel",
  "Accessibility Tools Framework",
  "EASE",
  "Aidge",
  "Babel",
  "BIRT",
  "CogniCrypt",
  "Collections",
  "CommaSuite",
  "Common Build Infrastructure",
  "Common Security Infrastructure",
  "Corinthian",
  "Daanse - Data and Analysis Services",
  "Dash",
  "Dataspace Components",
  "Dataspace TCK",
  "Deeplearning4j",
  "DROPS",
  "Dynamic Languages Toolkit",
  "e(fx)clipse",
  "EclEmma",
  "EGerrit",
  "EGit",
  "ESCET",
  "Free BIRD Tools",
  "Furo",
  "Graphene",
  "Handly",
  "iceoryx",
  "ImageN",
  "IoT-Testware",
  "jbom",
  "JGit",
  "Jifa",
  "JNoSQL",
  "JustJ",
  "LemMinX",
  "LSAT",
  "LSP4E",
  "LSP4J",
  "LSP4Jakarta",
  "LSP4MP",
  "Lyo",
  "Maven Integration - m2eclipse",
  "N4JS",
  "Nebula - Supplemental Widgets for SWT",
  "Nebula Incubator",
  "Nebula NatTable",
  "OMR",
  "Open Standard Business Platform",
  "Open System Engineering Environment",
  "OpenJ9",
  "openK Core Modules",
  "openK User Modules",
  "OS-Gov",
  "Packager",
  "Packaging Project",
  "Marketplace Client",
  "Passage",
  "Plato",
  "PASS",
  "Qrisp",
  "RCP Testing Tool",
  "RDF4J",
  "RedDeer",
  "Repairnator",
  "SCAVA",
  "Scout",
  "sensiNact",
  "Serializer",
  "Signalling Engineering Toolbox",
  "Sisu",
  "Spatio-Temporal Epidemiological Modeler",
  "Steady",
  "Store",
  "Subversive SVN Team Provider",
  "SW360",
  "SWTBot",
  "TEA",
  "TM4E",
  "TRACE4CPS",
  "Transformer",
  "Tycho",
  "UOMo",
  "User Storage Service SDK",
  "Vhant",
  "XFSC",
  "Xpanse",
  "XWT",
  "MicroProfile",
  "OSGi Specification Project",
  "OSGi Technology Project"
],
"Tools": [
  "aCute",
  "Andmore",
  "AspectJ",
  "Buildship",
  "CDT",
  "Corrosion",
  "Dartboard",
  "Data Tools Platform",
  "Graphical Editing Framework",
  "Linux Tools",
  "Lua Development Tools",
  "Memory Analyzer",
  "Mylyn",
  "Object Teams",
  "Oomph",
  "Orbit Project",
  "PHP Development Tools",
  "ShellWax",
  "Target Communication Framework",
  "Target Management",
  "Titan",
  "TOMLed",
  "Trace Compass",
  "Trace Compass Incubator",
  "Wild Web Developer",
  "WindowBuilder",
  "EGL Development Tools",
  "Sequoyah"
],
"Science": [
  "Advanced Visualization Project",
  "ChemClipse",
  "DAWNSci",
  "January",
  "Rich Beans",
  "Scanning",
  "StatET: Tooling for the R language",
  "SWTChart",
  "TeXlipse",
  "XACC",
  "The Eclipse Integrated Computational Environment"
],
"WebTools": [
  "Dali Java Persistence Tools",
  "JavaScript Development Tools",
  "Server Tools",
  "Tools for Faces",
  "Web Services Tools",
  "WTP Source Editing",
  "Java EE Module Configuration Editors",
  "Web Tools Common",
  "Webtools Releng",
  "WTP Java EE Tools"
]
};

var categories = ["Automotive", "DT", "ECD","Eclipse Project","EE4J","Adoptium","IoT","Location Tech","Modeling","PolarSys","Runtime","SOA","Technology","Tools","Science","WebTools"];

function populateCombinedDropdown() {
  var combinedDropdown = document.getElementById('txt_ide');
  combinedDropdown.innerHTML = ''; 

  var defaultOption = document.createElement('option');
  defaultOption.textContent = 'Select a project';
  defaultOption.disabled = true;
  defaultOption.selected = true;
  combinedDropdown.appendChild(defaultOption);

  for (var category in d) {
    var group = document.createElement('optgroup');
    group.label = category;

    d[category].forEach(function(product) {
      var option = document.createElement('option');
      option.value = product;
      option.textContent = product;
      group.appendChild(option);
    });

    combinedDropdown.appendChild(group);
  }
}

function filterDropdown() {
  var input, filter, optgroups, options, i, j, hasVisibleChildren;
  input = document.getElementById('searchInput');
  filter = input.value.toUpperCase();
  optgroups = document.getElementById('txt_ide').getElementsByTagName('optgroup');

  for (i = 0; i < optgroups.length; i++) {
    options = optgroups[i].getElementsByTagName('option');
    hasVisibleChildren = false;
    for (j = 0; j < options.length; j++) {
      if (options[j].textContent.toUpperCase().indexOf(filter) > -1) {
        options[j].style.display = "";
        hasVisibleChildren = true;
      } else {
        options[j].style.display = "none";
      }
    }
    optgroups[i].style.display = hasVisibleChildren ? "" : "none";
  }
}

document.addEventListener('DOMContentLoaded', function() {
  populateCombinedDropdown();
});

document.getElementById('searchInput').addEventListener('keyup', filterDropdown);